============================= test session starts ==============================
platform linux2 -- Python 2.7.18, pytest-4.6.9, py-1.8.1, pluggy-0.13.0
rootdir: /home/sonic/nac
collected 1 item

pytest_ex1.py F                                                          [100%]

=================================== FAILURES ===================================
____________________________ test_nac_functionality ____________________________

    def test_nac_functionality():
        ip_address1 = '172.30.25.67'
        username1 = 'sonic'
        password1 = 'admin123'
        ip_address2 = '172.30.25.102'
        username2 = 'admin'
        password2 = 'YourPaSsWoRd'
        ip_address3 = '172.30.25.93'
        username3 = 'sonic'
        password3 = 'admin123'
    
    
        client1 = paramiko.SSHClient()
        client1.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    
        client2 = paramiko.SSHClient()
        client2.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    
        client3 = paramiko.SSHClient()
        client3.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    
        try:
            # Connect to the first device (Supplicant PC)
            client1.connect(ip_address1, username=username1, password=password1)
    
            # Configuring IP on the Supplicant PC
            cmd_sup_ip = "sudo ifconfig enp7s0f3 70.0.0.10"  # sample
            stdin, stdout, stderr = client1.exec_command(cmd_sup_ip)
            cmd_sup_ip_output = stdout.read().decode()
            print(cmd_sup_ip_output)
            if "inet 70.0.0.10" in cmd_sup_ip_output:
                print("Yes")
            else:
                print("Invalid IP")
    
    
            client2.connect(ip_address2, username=username2, password=password2)
    
            cmd_reload_config = "sudo config reload -y"
            stdin, stdout, stderr = client2.exec_command(cmd_reload_config)
            cmd_reload_config = stdout.read().decode()
>           time.sleep(30)
E           NameError: global name 'time' is not defined

pytest_ex1.py:79: NameError
----------------------------- Captured stdout call -----------------------------

Invalid IP
=============================== warnings summary ===============================
/usr/local/lib/python2.7/dist-packages/paramiko/transport.py:33
  /usr/local/lib/python2.7/dist-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
    from cryptography.hazmat.backends import default_backend

-- Docs: https://docs.pytest.org/en/latest/warnings.html
==================== 1 failed, 1 warnings in 32.97 seconds =====================
